// Regenerates `oracle.json` from three.js' own `HDRLoader.parse` and
// `DataUtils`, so `tests/hdr_loader.rs` grades the Rust decoder against the
// JavaScript one rather than against itself.
//
//     node tests/hdr/gen.mjs            # THREE_JS_DIR, or ~/src/vendor/three.js
//
// `HDRLoader.js` imports from the bare specifier 'three', which node cannot
// resolve inside the vendor checkout, so it is copied to a temp file with that
// one import rewritten to the built module. Nothing in the vendor tree is
// touched.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const THREE = process.env.THREE_JS_DIR || path.join( os.homedir(), 'src/vendor/three.js' );
const build = pathToFileURL( path.join( THREE, 'build/three.module.js' ) ).href;

const tmp = fs.mkdtempSync( path.join( os.tmpdir(), 'hdr-oracle-' ) );
const patched = path.join( tmp, 'HDRLoader.mjs' );
fs.writeFileSync( patched, fs.readFileSync( path.join( THREE, 'examples/jsm/loaders/HDRLoader.js' ), 'utf8' )
	.replace( "from 'three'", `from '${ build }'` ) );

const { HDRLoader } = await import( pathToFileURL( patched ).href );
const { DataUtils, FloatType } = await import( build );

const dir = path.join( THREE, 'examples/textures/cube/pisaHDR' ) + '/';

const faces = [ 'px.hdr', 'nx.hdr', 'py.hdr', 'ny.hdr', 'pz.hdr', 'nz.hdr' ];

// FNV-1a 64 over the little-endian bytes of the Uint16Array.
function fnv1a64( u16 ) {
	let h = 0xcbf29ce484222325n;
	const p = 0x100000001b3n;
	const m = ( 1n << 64n ) - 1n;
	const bytes = new Uint8Array( u16.buffer, u16.byteOffset, u16.byteLength );
	for ( let i = 0; i < bytes.length; i ++ ) {
		h = ( ( h ^ BigInt( bytes[ i ] ) ) * p ) & m;
	}
	return h.toString( 16 ).padStart( 16, '0' );
}

const loader = new HDRLoader();
const out = { note: 'generated by gen.mjs over three.js r186 HDRLoader.parse; do not hand-edit', faces: [] };

for ( const name of faces ) {
	const buffer = fs.readFileSync( dir + name );
	const data = loader.parse( buffer.buffer.slice( buffer.byteOffset, buffer.byteOffset + buffer.byteLength ) );
	const u16 = data.data;
	// Fixed probe texels: a spread of indices, deterministic, no image knowledge.
	const probes = [];
	for ( const i of [ 0, 1, 2, 3, 255, 256, 257, 4096, 12345, 32768, 40000, 65535 ] ) {
		probes.push( { texel: i, rgba: [ u16[ i * 4 ], u16[ i * 4 + 1 ], u16[ i * 4 + 2 ], u16[ i * 4 + 3 ] ] } );
	}
	out.faces.push( {
		file: name,
		width: data.width,
		height: data.height,
		gamma: data.gamma,
		exposure: data.exposure,
		texels: u16.length / 4,
		fnv1a64: fnv1a64( u16 ),
		first: Array.from( u16.slice( 0, 16 ) ),
		last: Array.from( u16.slice( u16.length - 16 ) ),
		probes,
	} );
}

// Float path, for one face, as a second independent check of the RGBE scale.
{
	const f = new HDRLoader().setDataType( FloatType );
	const buffer = fs.readFileSync( dir + 'px.hdr' );
	const data = f.parse( buffer.buffer.slice( buffer.byteOffset, buffer.byteOffset + buffer.byteLength ) );
	out.px_float_first = Array.from( data.data.slice( 0, 16 ) );
}

// DataUtils.toHalfFloat, bit for bit.
const vals = [ 0, -0, 1, -1, 0.5, 2, 65504, -65504, 65505, 1e-8, 6.0975552e-5, 6.103515625e-5,
	5.960464477539063e-8, 3.0517578125e-5, 0.1, 1/3, 1023.5, 1e30, -1e30, 1.0000000000000002,
	2.9802322387695312e-8, 1.1920928955078125e-7, 100, 255, 256/255, 0.0000152587890625 ];
out.half = vals.map( v => ( { f32: Math.fround( v ), bits: new Uint32Array( new Float32Array( [ v ] ).buffer )[ 0 ], half: DataUtils.toHalfFloat( v ) } ) );
out.half_back = out.half.map( h => ( { half: h.half, bits: new Uint32Array( new Float32Array( [ DataUtils.fromHalfFloat( h.half ) ] ).buffer )[ 0 ] } ) );
out.half_back_extra = [ 0x0001, 0x03ff, 0x0400, 0x7bff, 0x8001, 0xfbff, 0x3555 ].map( h => ( { half: h, bits: new Uint32Array( new Float32Array( [ DataUtils.fromHalfFloat( h ) ] ).buffer )[ 0 ] } ) );

fs.writeFileSync( new URL( 'oracle.json', import.meta.url ), JSON.stringify( out, null, '\t' ) + '\n' );
console.log( JSON.stringify( out.faces[ 0 ], null, 1 ).slice( 0, 800 ) );
console.log( 'halfs', out.half.length );

fs.rmSync( tmp, { recursive: true, force: true } );
