//! Tests for `src/cluster.rs`. d3-hierarchy 3.1.2 ships no
//! `test/cluster-test.js` (test/ holds only data/, hierarchy/, pack/, treemap/
//! and stratify-test.js), so every expectation below was generated by running
//! the vendor JS itself, from /home/tom/src/vendor/d3-hierarchy, with:
//!
//! ```sh
//! node --input-type=module -e 'import {hierarchy, cluster} from "/home/tom/src/vendor/d3-hierarchy/src/index.js"; import fs from "fs"; const data = JSON.parse(fs.readFileSync("/home/tom/src/vendor/d3-hierarchy/test/data/simple.json")); const root = hierarchy(data).sum(d => d.value); cluster()(root); console.log(JSON.stringify(root.descendants().map(d => [d.depth, d.height, d.value, d.x, d.y])));'
//! ```
//!
//! and the same one-liner with `cluster().size([100, 200])`,
//! `cluster().nodeSize([10, 20])`,
//! `cluster().separation((a, b) => a.parent === b.parent ? 1 : 3)`,
//! `hierarchy({})` in place of the simple.json hierarchy, and
//! test/data/flare.json. The numbers are the JSON.stringify output verbatim,
//! which round-trips doubles exactly, so `assert_eq!` on f64 is bit equality.

use d3_hierarchy::cluster::Cluster;
use d3_hierarchy::{hierarchy, Tree};
use serde_json::json;

fn simple() -> serde_json::Value {
    json!({"children": [
        {"children": [{"value": 1}, {"value": 2}, {"value": 3}]},
        {"children": [{"value": 4}, {"value": 3}, {"value": 2}]}
    ]})
}

fn value(d: &serde_json::Value) -> f64 {
    d.get("value").and_then(|v| v.as_f64()).unwrap_or(f64::NAN)
}

/// `root.descendants().map(d => [d.depth, d.height, d.value, d.x, d.y])`.
fn dump(t: &Tree) -> Vec<(usize, usize, Option<f64>, f64, f64)> {
    t.descendants(t.root)
        .into_iter()
        .map(|i| {
            let n = &t.nodes[i];
            (n.depth, n.height, n.value, n.x, n.y)
        })
        .collect()
}

#[test]
fn cluster_default_size_1x1() {
    let mut root = hierarchy(&simple());
    root.sum(value);
    Cluster::new().cluster(&mut root);
    assert_eq!(
        dump(&root),
        vec![
            (0, 2, Some(15.0), 0.5, 0.0),
            (1, 1, Some(6.0), 0.25, 0.5),
            (1, 1, Some(9.0), 0.75, 0.5),
            (2, 0, Some(1.0), 0.125, 1.0),
            (2, 0, Some(2.0), 0.25, 1.0),
            (2, 0, Some(3.0), 0.375, 1.0),
            (2, 0, Some(4.0), 0.625, 1.0),
            (2, 0, Some(3.0), 0.75, 1.0),
            (2, 0, Some(2.0), 0.875, 1.0),
        ]
    );
}

#[test]
fn cluster_default_equals_cluster_new() {
    let mut a = hierarchy(&simple());
    a.sum(value);
    Cluster::default().cluster(&mut a);
    let mut b = hierarchy(&simple());
    b.sum(value);
    Cluster::new().cluster(&mut b);
    assert_eq!(dump(&a), dump(&b));
}

#[test]
fn cluster_size_100x200() {
    let mut root = hierarchy(&simple());
    root.sum(value);
    Cluster::new().size([100.0, 200.0]).cluster(&mut root);
    assert_eq!(
        dump(&root),
        vec![
            (0, 2, Some(15.0), 50.0, 0.0),
            (1, 1, Some(6.0), 25.0, 100.0),
            (1, 1, Some(9.0), 75.0, 100.0),
            (2, 0, Some(1.0), 12.5, 200.0),
            (2, 0, Some(2.0), 25.0, 200.0),
            (2, 0, Some(3.0), 37.5, 200.0),
            (2, 0, Some(4.0), 62.5, 200.0),
            (2, 0, Some(3.0), 75.0, 200.0),
            (2, 0, Some(2.0), 87.5, 200.0),
        ]
    );
}

#[test]
fn cluster_node_size_10x20() {
    let mut root = hierarchy(&simple());
    root.sum(value);
    Cluster::new().node_size([10.0, 20.0]).cluster(&mut root);
    assert_eq!(
        dump(&root),
        vec![
            (0, 2, Some(15.0), 0.0, 0.0),
            (1, 1, Some(6.0), -20.0, 20.0),
            (1, 1, Some(9.0), 20.0, 20.0),
            (2, 0, Some(1.0), -30.0, 40.0),
            (2, 0, Some(2.0), -20.0, 40.0),
            (2, 0, Some(3.0), -10.0, 40.0),
            (2, 0, Some(4.0), 10.0, 40.0),
            (2, 0, Some(3.0), 20.0, 40.0),
            (2, 0, Some(2.0), 30.0, 40.0),
        ]
    );
}

#[test]
fn cluster_custom_separation() {
    let mut root = hierarchy(&simple());
    root.sum(value);
    Cluster::new()
        .separation(|t: &Tree, a, b| {
            if t.nodes[a].parent == t.nodes[b].parent {
                1.0
            } else {
                3.0
            }
        })
        .cluster(&mut root);
    assert_eq!(
        dump(&root),
        vec![
            (0, 2, Some(15.0), 0.5, 0.0),
            (1, 1, Some(6.0), 0.25, 0.5),
            (1, 1, Some(9.0), 0.75, 0.5),
            (2, 0, Some(1.0), 0.15, 1.0),
            (2, 0, Some(2.0), 0.25, 1.0),
            (2, 0, Some(3.0), 0.35, 1.0),
            (2, 0, Some(4.0), 0.65, 1.0),
            (2, 0, Some(3.0), 0.75, 1.0),
            (2, 0, Some(2.0), 0.85, 1.0),
        ]
    );
}

#[test]
fn cluster_single_node() {
    // The `root.y ? node.y / root.y : 1` branch: root.y is 0, so y is 0.
    let mut root = hierarchy(&json!({}));
    Cluster::new().cluster(&mut root);
    assert_eq!(dump(&root), vec![(0, 0, None, 0.5, 0.0)]);
}

#[test]
fn cluster_single_node_node_size() {
    let mut root = hierarchy(&json!({}));
    Cluster::new().node_size([10.0, 20.0]).cluster(&mut root);
    assert_eq!(dump(&root), vec![(0, 0, None, 0.0, 0.0)]);
}

#[test]
fn cluster_flare() {
    let path = "/home/tom/src/vendor/d3-hierarchy/test/data/flare.json";
    let text = match std::fs::read_to_string(path) {
        Ok(t) => t,
        // The vendor tree is not part of this crate; skip rather than fail if
        // it is not present.
        Err(_) => return,
    };
    let data: serde_json::Value = serde_json::from_str(&text).unwrap();
    let mut root = hierarchy(&data);
    root.sum(value);
    Cluster::new().cluster(&mut root);

    let d = root.descendants(root.root);
    assert_eq!(d.len(), 252);

    let named = |name: &str| -> (usize, usize, Option<f64>, f64, f64) {
        let i = *d
            .iter()
            .find(|&&i| root.nodes[i].data["name"] == name)
            .unwrap();
        let n = &root.nodes[i];
        (n.depth, n.height, n.value, n.x, n.y)
    };

    assert_eq!(named("flare"), (0, 4, Some(956129.0), 0.3250502804078898, 0.0));
    assert_eq!(
        named("analytics"),
        (1, 2, Some(48716.0), 0.029182879377431907, 0.5)
    );
    assert_eq!(
        named("AgglomerativeCluster"),
        (3, 0, Some(3938.0), 0.0038910505836575876, 1.0)
    );
    assert_eq!(
        named("Easing"),
        (2, 0, Some(17010.0), 0.054474708171206226, 1.0)
    );
    assert_eq!(
        named("TreeMapLayout"),
        (4, 0, Some(9191.0), 0.9649805447470817, 1.0)
    );
    assert_eq!(
        named("ArrayInterpolator"),
        (3, 0, Some(1983.0), 0.06614785992217899, 1.0)
    );
}
