// Regenerates `oracle.json` from three.js' own `LUTCubeLoader`,
// `LUT3dlLoader` and `LUTImageLoader`, so `tests/loaders_lut.rs` grades the
// Rust loaders against the JavaScript ones rather than against themselves.
//
//     node tests/lut/gen.mjs            # THREE_JS_DIR, or ~/src/vendor/three.js
//
// The two text loaders run under node: `parse()` is pure string work. Their
// `.js` files import from the bare specifier 'three', which node cannot
// resolve inside the vendor checkout, so each is copied to a temp file with
// that one import rewritten to the built module (as `tests/hdr/gen.mjs`
// does). Nothing in the vendor tree is touched.
//
// `LUTImageLoader` needs `TextureLoader` and a 2D canvas, so it runs in the
// Chrome that three.js' own `npm ci` downloads (puppeteer, headless, no
// WebGPU involved), over a local server rooted at the checkout, with the real
// `examples/jsm/loaders/LUTImageLoader.js` resolved through an import map.
//
// Besides the vendor LUT files, a handful of synthetic inputs pin down the
// quirks the port reproduces: the multiline data-point regex (CRLF, trailing
// spaces, tabs, leading spaces, U+2028), JS `Number()` on malformed tokens,
// `Uint8Array` stores of out-of-range values, rows past `size³`, the 3dl grid
// line that also matches the data-point regex, and the `maxValue = 0` NaN.
// Float data is recorded as `Float32Array` bit patterns so NaN survives JSON.

import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const THREE = process.env.THREE_JS_DIR || path.join( os.homedir(), 'src/vendor/three.js' );
const build = pathToFileURL( path.join( THREE, 'build/three.module.js' ) ).href;

const tmp = fs.mkdtempSync( path.join( os.tmpdir(), 'lut-oracle-' ) );

async function importPatched( name ) {

	const patched = path.join( tmp, `${name}.mjs` );
	fs.writeFileSync( patched, fs.readFileSync( path.join( THREE, `examples/jsm/loaders/${name}.js` ), 'utf8' )
		.replace( "from 'three'", `from '${ build }'` ) );
	return import( pathToFileURL( patched ).href );

}

const { LUTCubeLoader } = await importPatched( 'LUTCubeLoader' );
const { LUT3dlLoader } = await importPatched( 'LUT3dlLoader' );
const { FloatType } = await import( build );

// FNV-1a 64 over bytes.
function fnv1a64( bytes ) {

	let h = 0xcbf29ce484222325n;
	const p = 0x100000001b3n;
	const m = ( 1n << 64n ) - 1n;
	for ( let i = 0; i < bytes.length; i ++ ) h = ( ( h ^ BigInt( bytes[ i ] ) ) * p ) & m;
	return h.toString( 16 ).padStart( 16, '0' );

}

const f32Bytes = ( f32 ) => new Uint8Array( f32.buffer, f32.byteOffset, f32.byteLength );
const f32Bits = ( f32 ) => Array.from( new Uint32Array( f32.buffer, f32.byteOffset, f32.length ) );

function run( parse ) {

	try {

		return parse();

	} catch ( error ) {

		return { error: error.message };

	}

}

const out = { note: 'generated by tests/lut/gen.mjs over three.js r187 LUTCubeLoader, LUT3dlLoader and LUTImageLoader; do not hand-edit' };

// --- the vendor files --------------------------------------------------------

const lutDir = path.join( THREE, 'examples/luts' ) + '/';

out.cube = [];
for ( const file of [ 'Bourbon 64.CUBE', 'Chemical 168.CUBE', 'Clayton 33.CUBE', 'Cubicle 99.CUBE', 'Remy 24.CUBE' ] ) {

	const text = fs.readFileSync( lutDir + file, 'utf8' );
	const u8 = new LUTCubeLoader().parse( text );
	const f32 = new LUTCubeLoader().setType( FloatType ).parse( text );
	const d = u8.texture3D.image.data;
	out.cube.push( {
		file,
		title: u8.title,
		size: u8.size,
		domainMin: u8.domainMin.toArray(),
		domainMax: u8.domainMax.toArray(),
		u8: fnv1a64( d ),
		f32: fnv1a64( f32Bytes( f32.texture3D.image.data ) ),
		first: Array.from( d.slice( 0, 16 ) ),
		last: Array.from( d.slice( - 16 ) ),
		f32First: f32Bits( f32.texture3D.image.data.slice( 0, 8 ) ),
	} );

}

out.threeDl = [];
for ( const file of [ 'Presetpro-Cinematic.3dl' ] ) {

	const text = fs.readFileSync( lutDir + file, 'utf8' );
	const u8 = new LUT3dlLoader().parse( text );
	const f32 = new LUT3dlLoader().setType( FloatType ).parse( text );
	const d = u8.texture3D.image.data;
	out.threeDl.push( {
		file,
		size: u8.size,
		u8: fnv1a64( d ),
		f32: fnv1a64( f32Bytes( f32.texture3D.image.data ) ),
		first: Array.from( d.slice( 0, 16 ) ),
		last: Array.from( d.slice( - 16 ) ),
		f32First: f32Bits( f32.texture3D.image.data.slice( 0, 8 ) ),
	} );

}

// --- synthetic inputs ----------------------------------------------------------

const cubeInputs = {
	// CRLF, a title on a later line, a domain, trailing spaces, a tab-separated
	// row and a leading-space row (both skipped), a malformed token (NaN -> 0),
	// out-of-range values (wrap mod 256), U+2028 as a line break, and more rows
	// than size³ (the extra stores land past the end and are dropped).
	quirks: '# comment\r\nLUT_3D_SIZE 2\r\nDOMAIN_MIN 0 0 0\r\nDOMAIN_MAX 1 1.5 1\r\nTITLE "Quirks"\r\n'
		+ '0 0 0   \r\n1e 0.5 1\r\n0\t0\t0\r\n 0.1 0.2 0.3\r\n-0.5 2 1.0001\r\n'
		+ '0.25 0.5 0.75 0.2 0.4 0.6\n1 1 1\n0.1 0.1 0.1\n0.9 0.9 0.9\n0.3 0.3 0.3\n0.7 0.7 0.7\n',
	// No title, LF only, a short table (unfilled texels stay 0).
	short: 'LUT_3D_SIZE 2\n0.5 0.5 0.5\n+1 .5 1.\n',
	// TITLE's first occurrence does not match the regex, the second does; the
	// title spans a line break.
	title: 'TITLE x\nTITLE  "two\nlines"\nLUT_3D_SIZE 1\n1 0 0\n',
	missingSize: 'TITLE "none"\n0 0 0\n',
	badDomain: 'LUT_3D_SIZE 1\nDOMAIN_MIN 0 2 0\nDOMAIN_MAX 1 1 1\n0 0 0\n',
};

out.cubeSynthetic = {};
for ( const [ name, text ] of Object.entries( cubeInputs ) ) {

	out.cubeSynthetic[ name ] = {
		input: text,
		u8: run( () => {

			const r = new LUTCubeLoader().parse( text );
			return { title: r.title, size: r.size, domainMin: r.domainMin.toArray(), domainMax: r.domainMax.toArray(), data: Array.from( r.texture3D.image.data ) };

		} ),
		f32: run( () => {

			const r = new LUTCubeLoader().setType( FloatType ).parse( text );
			return { size: r.size, bits: f32Bits( r.texture3D.image.data ) };

		} ),
	};

}

const grid3 = '0 511 1022\n';
let rows3 = '';
for ( let i = 0; i < 27; i ++ ) rows3 += `${( i * 37 ) % 1024} ${( i * 101 ) % 1024} ${( i * 211 ) % 4096}\n`;

const threeDlInputs = {
	// A size-3 grid: the grid line is three tokens, so it is also the first
	// data point, and every row after it shifts by one.
	grid3: `# header\n${ grid3 }${ rows3 }`,
	// All zeros: maxValue stays 0, log2( 0 ) = -Infinity, maxBitValue = 0 and
	// every colour is 0 / 0 = NaN.
	zeros: '0 1\n0 0 0\n0 0 0\n0 0 0\n0 0 0\n0 0 0\n0 0 0\n0 0 0\n0 0 0\n',
	// A grid line of only spaces: trim() leaves '', so the grid is [ 0 ], size
	// 1 and gridStep NaN.
	blankGrid: 'x\n   \n10 20 30\n',
	// A malformed point makes maxValue NaN.
	nan: '0 1\n1e 0 0\n4 4 4\n',
	inconsistent: '0 1 3\n',
	missingGrid: 'x\n1.5 2 3\n',
};

out.threeDlSynthetic = {};
for ( const [ name, text ] of Object.entries( threeDlInputs ) ) {

	out.threeDlSynthetic[ name ] = {
		input: text,
		u8: run( () => {

			const r = new LUT3dlLoader().parse( text );
			return { size: r.size, data: Array.from( r.texture3D.image.data ) };

		} ),
		f32: run( () => {

			const r = new LUT3dlLoader().setType( FloatType ).parse( text );
			return { size: r.size, bits: f32Bits( r.texture3D.image.data ) };

		} ),
	};

}

// --- LUTImageLoader, in the browser ------------------------------------------

const MIME = { '.js': 'text/javascript', '.png': 'image/png', '.html': 'text/html' };

const server = http.createServer( ( request, response ) => {

	const url = decodeURIComponent( new URL( request.url, 'http://x' ).pathname );
	if ( url === '/' ) {

		response.writeHead( 200, { 'content-type': 'text/html' } );
		response.end( `<!doctype html><title>lut reference</title>
<script type="importmap">{ "imports": { "three": "/build/three.module.js" } }</script>` );
		return;

	}

	const file = path.join( THREE, url );
	if ( ! file.startsWith( THREE ) || ! fs.existsSync( file ) ) {

		response.writeHead( 404 ).end();
		return;

	}

	response.writeHead( 200, { 'content-type': MIME[ path.extname( file ) ] || 'application/octet-stream' } );
	response.end( fs.readFileSync( file ) );

} );
await new Promise( ( resolve ) => server.listen( 0, '127.0.0.1', resolve ) );
const origin = `http://localhost:${ server.address().port }`;

const { default: puppeteer } = await import( pathToFileURL( path.join( THREE, 'node_modules/puppeteer/lib/puppeteer/puppeteer.js' ) ).href );
const browser = await puppeteer.launch( {
	executablePath: process.env.CHROME || await puppeteer.executablePath(),
	headless: true,
	args: [ '--no-sandbox' ],
} );

try {

	const page = await browser.newPage();
	await page.goto( `${ origin }/`, { waitUntil: 'load' } );
	out.image = await page.evaluate( async () => {

		const { LUTImageLoader } = await import( '/examples/jsm/loaders/LUTImageLoader.js' );

		function fnv1a64( bytes ) {

			let h = 0xcbf29ce484222325n;
			const p = 0x100000001b3n;
			const m = ( 1n << 64n ) - 1n;
			for ( let i = 0; i < bytes.length; i ++ ) h = ( ( h ^ BigInt( bytes[ i ] ) ) * p ) & m;
			return h.toString( 16 ).padStart( 16, '0' );

		}

		const result = [];
		for ( const file of [ 'NeutralLUT.png', 'B&WLUT.png', 'NightLUT.png' ] ) {

			for ( const flip of [ false, true ] ) {

				const loader = new LUTImageLoader();
				loader.flip = flip;
				const lut = await loader.loadAsync( '/examples/luts/' + encodeURIComponent( file ) );
				const d = lut.texture3D.image.data;
				const probes = [];
				for ( const t of [ 0, 1, 31, 32, 1023, 1024, 5000, 17000, 31743, 31744, 32767 ] ) {

					probes.push( { texel: t, rgba: Array.from( d.slice( t * 4, t * 4 + 4 ) ) } );

				}

				result.push( { file, flip, size: lut.size, bytes: d.length, u8: fnv1a64( d ), probes } );

			}

		}

		return result;

	} );

} finally {

	await browser.close();
	server.close();

}

fs.writeFileSync( new URL( 'oracle.json', import.meta.url ), JSON.stringify( out, null, '\t' ) + '\n' );
console.log( JSON.stringify( out.cube.map( c => [ c.file, c.title, c.u8, c.f32 ] ) ) );
console.log( JSON.stringify( out.image.map( c => [ c.file, c.flip, c.size, c.u8 ] ) ) );

fs.rmSync( tmp, { recursive: true, force: true } );
